"""This script is for learning German."""

from random import shuffle
from collections import ChainMap
from itertools import permutations
from re import sub
import tkinter as tk

VERBS_DICT = {
    "dürfen": "be allowed (may)",
    "können": "be able (can)",
    "mögen": "like",
    "möchten": "would like",
    "müssen": "have to (must)",
    "wollen": "want",
    "sollen": "ought to / shall",
    "brauchen": "need to",
    "denken": "think",
    "wissen": "know (a fact)",
    "abhängen": "depend",
    "kennen": "be familiar with",
    "erkennen": "recognise",
    "lernen": "learn",
    "umlernen": "retrain",
    "verlernen": "forget (something already learned)",
    "studieren": "study",
    "verstehen": "understand",
    "fragen": "ask (a question)",
    "wiederholen": "repeat",
    "vergessen": "forget",
    "erinnern": "remind",
    "sich erinnern": "remember",
    "glauben": "believe",
    "achten": "pay attention",
    "üben": "practice",
    "bedeuten": "mean",
    "erwarten": "expect",
    "versprechen": "promise",
    "empfehlen": "recommend",
    "antworten": "answer",
    "lehren / unterrichten": "teach",
    "erklären": "explain",
    "melden": "report",
    "vergleichen": "compare",
    "zustimmen": "agree",
    "helfen": "help",
    "teilen": "share",
    "bieten / anbieten": "offer",
    "verbieten": "forbid",
    "lügen": "lie (falshood)",
    "verraten": "betray",
    "hören": "hear / listen",
    "sprechen": "speak",
    "riechen": "smell",
    "reden": "talk",
    "sagen": "say",
    "lesen": "read",
    "schreiben": "write",
    "buchstabieren": "spell",
    "erzählen": "tell / narrate",
    "sehen": "see",
    "aussehen": "look like",
    "schauen": "look",
    "anschauen / sich ansehen": "watch / look at",
    "beobachten": "observe",
    "zeichnen": "draw",
    "zeigen": "show",
    "machen": "make / do",
    "tun": "do",
    "rufen": "call",
    "anrufen": "phone",
    "bleiben": "stay",
    "gehen": "go",
    "laufen": "walk / run",
    "rennen": "run",
    "fahren": "drive",
    "stehen": "stand",
    "sitzen": "sit",
    "springen": "jump",
    "warten": "wait",
    "fliegen": "fly",
    "hängen": "hang",
    "liegen": "lie (physically)",
    "kommen": "come",
    "bekommen": "get",
    "nehmen": "take",
    "mitnehmen": "take along",
    "holen": "fetch",
    "bringen": "bring",
    "geben": "give",
    "schenken": "gift",
    "senden / schicken": "send",
    "tragen": "carry",
    "stellen": "put",
    "packen": "pack",
    "werfen": "throw",
    "wegwerfen": "throw away",
    "bestellen": "order",
    "kaufen": "buy",
    "einkaufen": "shop",
    "verkaufen": "sell",
    "bezahlen": "pay",
    "zählen": "count",
    "kosten": "cost",
    "verdienen": "earn",
    "ausgeben": "spend (money)",
    "spenden": "donate",
    "suchen": "search",
    "arbeiten": "work",
    "wohnen": "live (reside)",
    "leben": "be alive",
    "schlafen": "sleep",
    "einschlafen": "fall asleep",
    "aufwachen": "wake up",
    "duschen": "shower",
    "kochen": "cook",
    "trinken": "drink",
    "essen": "eat",
    "sich entspannen": "relax oneself",
    "spielen": "play",
    "reinigen": "clean",
    "waschen": "wash",
    "aufräumen": "tidy up",
    "sich anziehen": "get dressed",
    "sich ausziehen": "get undressed",
    "sich rasieren": "shave oneself",
    "steigen": "climb / rise",
    "umsteigen": "transfer (vehicles)",
    "einsteigen": "get on",
    "aussteigen": "get off",
    "losgehen": "set off",
    "sich beeilen": "hurry up",
    "verspäten": "delay",
    "sich verspäten": "be late",
    "verschlafen": "oversleep",
    "ankommen": "arrive",
    "abfaren": "depart",
    "dauern": "last (take time)",
    "überdauern": "outlast",
    "reisen": "travel",
    "besuchen": "visit / attend",
    "einladen": "invite",
    "treffen": "meet",
    "sich treffen": "meet up",
    "benutzen": "use",
    "lösen": "solve / remove / untighten",
    "spannen": "tension / tighten",
    "gehören": "belong",
    "besitzen": "own",
    "ausmachen": "turn off",
    "anmachen": "turn on",
    "laden": "load",
    "hochladen": "upload",
    "herunterladen": "download",
    "aufladen": "charge (battery)",
    "schließen": "close",
    "aufschließen": "unlock",
    "öffnen": "open",
    "ziehen": "pull / move",
    "bauen": "build",
    "sich interessieren": "be interested in",
    "träumen": "dream",
    "lieben": "love",
    "hassen": "hate",
    "sich fühlen": "feel [czuć się]",
    "spüren": "sense",
    "erleben": "experience",
    "sich freuen": "be happy about [cieszyć się że / na]",
    "versuchen": "try (a task)",
    "probieren": "try (a thing)",
    "aufgeben": "give up",
    "verlieren": "lose",
    "gewinnen": "win",
    "erreichen": "achieve / reach",
    "vorhaben": "intend",
    "hoffen": "hope",
    "wünschen": "wish",
    "beenden": "finish",
    "beginnen / anfangen": "begin",
    "wählen / auswählen": "choose / select"}

ADVERBS_DICT = {
    "dann": "then",
    "also": "so",
    "auch": "as well / also / too",
    "fast": "almost / nearly",
    "etwas": "something / a bit",
    "etwa": "about / roughly",
    "dort": "there [tam]",
    "noch": "still / yet",
    "jetzt": "now",
    "aber": "but",
    "oder": "or",
    "man": "(some)one",
    "bald": "soon",
    "nur": "just / only",
    "ohne": "without",
    "statt": "instead of",
    "ziemlich": "pretty / quite",
    "genau": "exactly",
    "deshalb / deswegen": "therefore",
    "immer": "always",
    "manchmal": "sometimes",
    "sofort": "immediately",
    "vielleicht": "perhaps",
    "genug": "enough",
    "wieder": "again",
    "wider": "against",
    "obwohl": "although",
    "ob": "whether",
    "dass": "that [że]",
    "trotz": "despite",
    "weder noch": "neither nor",
    "nie / niemals": "never",
    "bereits / schon": "already",
    "wenn / als": "when",
    "denn / weil": "because",
    "besonders": "especially",
    "oft": "often",
    "selten": "rarely",
    "sehr": "very",
    "kaum": "hardly",
    "eigentlich": "actually",
    "wirklich": "really",
    "wo": "where?",
    "woher": "where from?",
    "wohin": "where to?",
    "wann": "when?",
    "was": "what?",
    "wer": "who?",
    "wie": "how?",
    "warum / wieso": "why?"}

####################################################################################################

def translate_word(dictionaries, direction):
    if direction not in ["german to english", "english to german"]:
        print(f"Incorrect direction argument '{direction}', stopping.")
        return False

    dictionaries = list(ChainMap(*dictionaries).items())
    shuffle(dictionaries)
    if direction == "german to english":
        # Removing all round and square brackets, and everything inside them
        dictionaries = [(sub(r"s*[\[\(].+[\]\)]s*", "", item[1]), item[0])
                        for item in dictionaries]

    for words in dictionaries:
        if "/" not in words[0]:
            right_answers = [words[0]]
        else:
            answer_pieces = words[0].split(" / ")
            rearranged = permutations(answer_pieces, len(answer_pieces))
            right_answers = [" / ".join(item) for item in rearranged]

        answer = input(f"Translate '{words[1]}':\n")
        if answer in right_answers:
            print("Correct.")
        else:
            print(f"Wrong - the right answer is '{words[0]}'")

    print("All finished.")
    return True

####################################################################################################

# German special chacters - ä ü ö ß
translate_word([VERBS_DICT, ADVERBS_DICT], "english to german")

#TODO: translate sentences, GUI with German characters, verb conjugation and tenses, pronunciation
