"""This file contains information about the German language."""

VERBS_DICT = {
    "dürfen": "to be allowed to (may)",
    "können": "to be able to (can)",
    "mögen": "to like",
    "möchten": "would like to",
    "müssen": "to have to (must)",
    "wollen": "to want",
    "sollen": "to ought to (shall)",
    "werden": "will / to become", # Needs voice
    "haben": "to have", # Needs voice
    "sein": "to be", # Needs voice
    "brauchen": "to need",
    "denken": "to think",
    "wissen": "to know (a fact)",
    "abhängen": "to depend",
    "kennen": "to be familiar with",
    "erkennen": "to recognise",
    "lernen": "to learn",
    "umlernen": "to retrain",
    "verlernen": "to forget (something already learned)",
    "studieren": "to study",
    "verstehen": "to understand",
    "fragen": "to ask (a question)",
    "wiederholen": "to repeat",
    "vergessen": "to forget",
    "erinnern": "to remind",
    "sich erinnern": "to remember",
    "glauben": "to believe",
    "achten": "to pay attention",
    "üben": "to practice",
    "bedeuten": "to mean",
    "erwarten": "to expect",
    "versprechen": "to promise",
    "empfehlen": "to recommend",
    "antworten": "to answer",
    "lehren / unterrichten": "to teach",
    "erklären": "to explain",
    "melden": "to report",
    "vergleichen": "to compare",
    "zustimmen": "to agree",
    "helfen": "to help",
    "teilen": "to share",
    "bieten / anbieten": "to offer",
    "verbieten": "to forbid",
    "lügen": "to lie (falshood)",
    "verraten": "to betray",
    "hören": "to hear / to listen",
    "sprechen": "to speak",
    "riechen": "to smell",
    "reden": "to talk",
    "sagen": "to say",
    "lesen": "to read",
    "schreiben": "to write",
    "buchstabieren": "to spell",
    "erzählen": "to tell / to narrate",
    "sehen": "to see",
    "aussehen": "to look like",
    "schauen": "to look",
    "anschauen / sich ansehen": "to watch / to look at",
    "beobachten": "to observe",
    "zeichnen": "to draw",
    "zeigen": "to show",
    "machen": "to make / to do",
    "tun": "to do",
    "rufen": "to call",
    "anrufen": "to phone",
    "bleiben": "to stay",
    "gehen": "to go",
    "laufen": "to walk / to run",
    "rennen": "to run",
    "fahren": "to drive",
    "stehen": "to stand",
    "sitzen": "to sit",
    "springen": "to jump",
    "warten": "to wait",
    "fliegen": "to fly",
    "hängen": "to hang",
    "liegen": "to lie (physically)",
    "kommen": "to come",
    "bekommen": "to get",
    "nehmen": "to take",
    "mitnehmen": "to take along",
    "holen": "to fetch",
    "bringen": "to bring",
    "geben": "to give",
    "schenken": "to gift",
    "senden / schicken": "to send",
    "tragen": "to carry",
    "stellen": "to put",
    "packen": "to pack",
    "werfen": "to throw",
    "wegwerfen": "to throw away",
    "bestellen": "to order",
    "kaufen": "to buy",
    "einkaufen": "to shop",
    "verkaufen": "to sell",
    "bezahlen": "to pay",
    "zählen": "to count",
    "kosten": "to cost",
    "verdienen": "to earn",
    "ausgeben": "to spend (money)",
    "spenden": "to donate",
    "suchen": "to search",
    "arbeiten": "to work",
    "wohnen": "to live (reside)",
    "leben": "to be alive",
    "schlafen": "to sleep",
    "einschlafen": "to fall asleep",
    "aufwachen": "to wake up",
    "duschen": "to shower",
    "kochen": "to cook",
    "trinken": "to drink",
    "essen": "to eat",
    "sich entspannen": "to relax oneself",
    "spielen": "to play",
    "reinigen": "to clean",
    "waschen": "to wash",
    "aufräumen": "to tidy up",
    "sich anziehen": "to get dressed",
    "sich ausziehen": "to get undressed",
    "sich rasieren": "to shave oneself",
    "steigen": "to climb / to rise",
    "umsteigen": "to transfer (vehicles)",
    "einsteigen": "to get on",
    "aussteigen": "to get off",
    "losgehen": "to set off",
    "sich beeilen": "to hurry up",
    "verspäten": "to delay",
    "sich verspäten": "to be late",
    "verschlafen": "to oversleep",
    "ankommen": "to arrive",
    "abfahren": "to depart",
    "dauern": "to last (take time)",
    "überdauern": "to outlast",
    "reisen": "to travel",
    "besuchen": "to visit / to attend",
    "einladen": "to invite",
    "treffen": "to meet",
    "sich treffen": "to meet up",
    "benutzen": "to use",
    "lösen": "to solve / to remove / to untighten",
    "spannen": "to tension / to tighten",
    "gehören": "to belong",
    "besitzen": "to own",
    "ausmachen": "to turn off",
    "anmachen": "to turn on",
    "laden": "to load",
    "hochladen": "to upload",
    "herunterladen": "to download",
    "aufladen": "to charge (battery)",
    "schließen": "to close",
    "aufschließen": "to unlock",
    "öffnen": "to open",
    "ziehen": "to pull / to move",
    "bauen": "to build",
    "sich interessieren": "to be interested in",
    "träumen": "to dream",
    "lieben": "to love",
    "hassen": "to hate",
    "sich fühlen": "to feel [czuć się]",
    "spüren": "to sense",
    "erleben": "to experience",
    "sich freuen": "to be happy about [cieszyć się że / na]",
    "versuchen": "to try (a task)",
    "probieren": "to try (a thing)",
    "aufgeben": "to give up",
    "verlieren": "to lose",
    "gewinnen": "to win",
    "erreichen": "to achieve / to reach",
    "vorhaben": "to intend",
    "hoffen": "to hope",
    "wünschen": "to wish",
    "beenden": "to finish",
    "beginnen / anfangen": "to begin",
    "wählen / auswählen": "to choose / to select"}

ADVERBS_DICT = {
    "dann": "then",
    "also": "so",
    "auch": "as well / also / too",
    "fast": "almost / nearly",
    "etwas": "something / a bit",
    "etwa": "about / roughly",
    "dort": "there [tam]",
    "noch": "still / yet",
    "jetzt": "now",
    "aber": "but",
    "oder": "or",
    "man": "(some)one",
    "bald": "soon",
    "nur": "just / only",
    "ohne": "without",
    "statt": "instead of",
    "ziemlich": "pretty / quite",
    "genau": "exactly",
    "deshalb / deswegen": "therefore",
    "immer": "always",
    "manchmal": "sometimes",
    "sofort": "immediately",
    "vielleicht": "perhaps",
    "genug": "enough",
    "wieder": "again",
    "wider": "against",
    "obwohl": "although",
    "ob": "whether",
    "dass": "that [że]",
    "trotz": "despite",
    "weder noch": "neither nor",
    "nie / niemals": "never",
    "bereits / schon": "already",
    "wenn / als": "when",
    "denn / weil": "because",
    "besonders": "especially",
    "oft": "often",
    "selten": "rarely",
    "sehr": "very",
    "kaum": "hardly",
    "eigentlich": "actually",
    "wirklich": "really",
    "trotzdem / dennoch": "nevertheless",
    "leider": "unfortunately", # Needs voice
    "wo": "where?",
    "woher": "where from?",
    "wohin": "where to?",
    "wann": "when?",
    "was": "what?",
    "wer": "who?",
    "wie": "how?",
    "warum / wieso": "why?"}
